#############################################################
## NOT FOR PRODUCTION USE.                                 ##
## THE CONTENT OF THIS FILE IS FOR LEARNING PURPOSES ONLY  ##
## created by David Surey, Amazon Web Services, 2020       ##
#############################################################

- name: create Policies for loadbalancer-controller
  cloudformation:
    profile: "{{ eksexample_aws_profilename }}"
    stack_name: "{{ eksexample_clustername }}-cluster-loadbalancercontroller-policy"
    state: present
    region: "{{ eksexample_region }}"
    template: "./cloudformation/eks-loadbalancer-controller-iam-policy.template.yaml"

- name: setup service account for alb-loadbalancer-controller
  delegate_to: "{{ EKSBastionInstancePublicIP }}"
  shell: >
    eksctl create iamserviceaccount \
    --name alb-loadbalancer-controller \
    --namespace kube-system \
    --cluster "{{ eksexample_clustername }}" \
    --attach-policy-arn "arn:aws:iam::{{ caller_info.account }}:policy/EKSloadbalancerControllerPolicy" \
    --approve \
    --region {{ eksexample_region }} \
    --override-existing-serviceaccounts

- name: deploy the alb-loadbalancer-controller
  delegate_to: "{{ EKSBastionInstancePublicIP }}"
  community.kubernetes.k8s: 
    state: present
    src: "./k8s/loadbalancer-controller/eks-loadbalancer-controller-{{ item }}.manifest.yaml'"
  loop: 
    - cert-manager
    - cert-manager-legacy
    - deployment